project:
  type: book
  output-dir: docs

book:
  title: "Tidyverse code review principles"
  author: "Davis Vaughan"
  chapters:
    - index.qmd
    - part: reviewer/index.qmd
      chapters:
      - reviewer/purpose.qmd
      - reviewer/aspects.qmd
      - reviewer/navigate.qmd
      - reviewer/speed.qmd
      - reviewer/comments.qmd
      - reviewer/pushback.qmd
    - part: developer/index.qmd
      chapters:
      - developer/descriptions.qmd
      - developer/small.qmd
      - developer/handling-comments.qmd

format:
  html:
    theme: cosmo

editor: visual

